// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cihvsbhkclvvigclenla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpaHZzYmhrY2x2dmlnY2xlbmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDg2OTgsImV4cCI6MjA2NDY4NDY5OH0.xxbmkXhbdv3hG8-FOnXE4GZj18asF-ioopc2etNfDp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);